// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Utils$AdventOfCode2018Reasonml = require("./Utils.bs.js");

function parseInputFile(fileName) {
  return Utils$AdventOfCode2018Reasonml.readRows(fileName).map(Caml_format.caml_int_of_string);
}

exports.parseInputFile = parseInputFile;
/* Utils-AdventOfCode2018Reasonml Not a pure module */
