// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

function parseInputFile(fileName) {
  return List.map(Caml_format.caml_int_of_string, List.filter((function (line) {
                      return line !== "";
                    }))($$Array.to_list(Fs.readFileSync(fileName, "utf8").split("\n"))));
}

exports.parseInputFile = parseInputFile;
/* fs Not a pure module */
