// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

var result = Fs.readFileSync("inputs/Day1Part1.txt", "utf8").split("\n").filter((function (line) {
            return line !== "";
          })).map((function (prim) {
          return Number(prim);
        })).reduce((function (a, b) {
        return a + b;
      }), 0.0);

console.log(result);

exports.result = result;
/* result Not a pure module */
